language: node_js

sudo: required

services:
- docker

node_js:
- 8

before_install:
- npm run build
- docker ps -a
- docker run sjones6/arsenal-dock /bin/sh -c "cd /app; npm test"

script:
- npm test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push sjones6/arsenal-dock;
    fi